### PR TITLE
Updated build and nuget refs to .NET 8 RC2

### PR DESCRIPTION
**Pull request by daghsentinel**

### CODE REVIEW

**Review by seriouz — COMMENTED** [review]
Seems good, but i want to test it locally at the weekend.

**Comment by robford123** [comment]
I'd hold off on updating until it's released, it's only a couple of weeks.

**Comment by daghsentinel** [comment]
> I'd hold off on updating until it's released, it's only a couple of weeks.

Why is that? The RC releases are production ready and fully supported. The Nov 14 GA release will not change tht.

**Comment by seriouz** [comment]
I think that most people use the Docker image anyway and for them it is not really important which version runs under the hood, and like @daghsentinel said; The rc versions are marked by Microsoft as Production-Ready.

I tested the PR locally and it worked without any issues.

**Comment by daghsentinel** [comment]
Still one reviewer and one awaiting workflow approval to go. How can I speed up the PR process? I'd love to contribute, but this isn't really making any progress.

**Comment by seriouz** [comment]
@daghsentinel On Nov 14. .NET 8 gets released. I would suggest that we go directly to 8.0 in 8 days. You could already adapt the reference to in in the source files instead of "-rc.2" and we merge this in 8 days on the release day.

**Review by seriouz — COMMENTED** [review]
Seems good to me! I'll test & merge it in 8 days when the release is made.

**Comment by seriouz** [comment]
Waiting for Npgsql.EntityFrameworkCore.PostgreSQL 8.0.0 release...

**Review by seriouz — APPROVED** [review]
.NET 8 has been released; Here we go!

**Comment by seriouz** [comment]
@robford123 I can't approve nor merge requests. Can you look into that?

**Comment by robford123** [comment]
Try it again. I'm not sure why but members didn't have write access.

**Comment by daghsentinel** [comment]
Changes approved, but still 1 workflow awaiting approval

**Pull request merged**
