### PR TITLE
add arm docker image support

### PR DESCRIPTION
**Pull request by cw-sarvesh**
Summary of the changes (in less than 80 chars)

 *Add arm and amd both architecture image support in release pipeline

[Addresses https://github.com/bagetter/BaGet/issues/123](https://github.com/bagetter/BaGetter/issues/134)

### CODE REVIEW

**Comment by Regenhardt** [comment]
Have you tested this? I'm not sure how I can test this other than pulling up an ARM machine on a cloud provider and running the image there.

**Comment by seriouz** [comment]
@cw-sarvesh Ah I see you have already made the change. I think this should work. @Regenhardt We should do a release with this. I can test it on a Raspberry Pi.

**Review by seriouz — APPROVED** [review]

**Review by ferarias — APPROVED** [review]

**Comment by Regenhardt** [comment]
Unfortunately I had to revert this to fix the docker hub release, please either test the next change before merging or make sure to provide it with the documentation where it says how multi-platform docker deploy works (for github actions in particular), because apparently something was missing from this try.

**Comment by Regenhardt** [comment]
Here's the job with error message. Unfortunately it's not very helpful to me as it just links to the general documentation:  
https://github.com/bagetter/BaGetter/actions/runs/8943379554/job/24567993878

**Pull request merged**
