### PR TITLE
Removed the docs files and hinted that the docs are now in another repo.

### PR DESCRIPTION
**Pull request by seriouz**
I removed the docs files and hinted that the docs are now in another repo to avoid confusion.

### CODE REVIEW

**Review by daghsentinel — APPROVED** [review]

**Comment by Regenhardt** [comment]
Was this necessary? I think the split between repos makes it way more complicated to keep the docs in sync with the app.

**Comment by seriouz** [comment]
I don't know the repos were split since the beginning. Probably we can somehow use the docs from the main repo but the docs compiler from the github.io repo. Any ideas?

**Comment by Regenhardt** [comment]
Why not keep the system like in the original BaGet, docs directory that gets compiled to a website? Looks like [this](https://github.com/loic-sharma/BaGet/blob/main/mkdocs.yml) is the config file for collecting everything into the website. Now if I could find the github action definition that executes it I'd link it but either I can't find it or it's hidden for me.

**Comment by seriouz** [comment]
@Regenhardt Can you look into this, how cross repo workflows are working?

**Pull request merged**
