### PR TITLE
Docker ARM support

### PR DESCRIPTION
**Pull request by seriouz**
I've looked into building ARM based Docker Images and this is the solution that worked on my private repo.
I tried the Docker image on my Raspberry Pi and it worked fine there.

This solves issue https://github.com/bagetter/BaGetter/issues/134

### CODE REVIEW

**Review by Regenhardt — COMMENTED** [review]
Can the current image be used on windows containers too? Would be nice to add windows to the build targets too then to keep those users happy. With docker desktop I could just switch to windows containers, but I'm not sure how to do that with podman yet so I can't test it right now.

**Comment by seriouz** [comment]
> Can the current image be used on windows containers too? Would be nice to add windows to the build targets too then to keep those users happy. With docker desktop I could just switch to windows containers, but I'm not sure how to do that with podman yet so I can't test it right now.

I don't know. Do you mean Windows Docker Container? I am not sure how to do this the correct way. Would need to figure this out and test this.
I would suggest to do this in another release.

**Comment by Regenhardt** [comment]
> > Can the current image be used on windows containers too? Would be nice to add windows to the build targets too then to keep those users happy. With docker desktop I could just switch to windows containers, but I'm not sure how to do that with podman yet so I can't test it right now.
> 
> I don't know. Do you mean Windows Docker Container? I am not sure how to do this the correct way. Would need to figure this out and test this. I would suggest to do this in another release.

If you have docker for windows, you can just right-click the symbol and "Switch to Windows containers". Then run the image to see if everything works.

**Review by Regenhardt — APPROVED** [review]
We can make the update announcement say we now provide specific images for linux and ARM, which implies no windows image for now.

**Pull request merged**
