### PR TITLE
Update packages to latest versions

### PR DESCRIPTION
**Pull request by robford123**
Updated all packages to latest versions. Removes some vulnerabilities, especially in the Postgres libraries.

### CODE REVIEW

**Comment by seriouz** [comment]
Hi @robford123 why did you add
```xml
  <ItemGroup>
    <PackageReference Update="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  ```
  in many csproj?

**Comment by robford123** [comment]
Upgrading the packages automatically added that in, I checked it built and tests ran ok.

**Comment by seriouz** [comment]
LoL I didn't know that Visual Studios test discovery isn't that good, so the packages is almost required when using Visual Studio.

**Comment by seriouz** [comment]
@robford123 Can you have a look into the merge conflicts?

**Comment by robford123** [comment]
@seriouz should be all good now

**Review by seriouz — COMMENTED** [review]
Okay

**Review by seriouz — APPROVED** [review]

**Comment by Regenhardt** [comment]
> Upgrading the packages automatically added that in, I checked it built and tests ran ok.

It should actually be in the Directory.Build.props of the test directory, not sure why it was added to the individual project files again.

**Pull request merged**
